name: clickplay

packages:
  - app/**
  - packages/**
  - widgetbook/**

scripts:
  bootstrap:
    run: melos bootstrap
    description: Bootstrap all packages

  widgetbook:build:
    run: cd widgetbook && dart run build_runner build -d
    description: Build the widgetbook

  widgetbook:
    run: melos run widgetbook:build && cd widgetbook && flutter run -d chrome
    description: Run the widgetbook

  app:
    run: cd app && flutter run -d chrome
    description: Run the app

  emulator:
    run: firebase emulators:start
    description: Launch firebase emulator

  test:
    run: melos exec --dir-exists="test" -c 1 -- "flutter test --coverage"
    description: Run all tests

ide:
  intellij: false
