name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.1
  intl: ^0.19.0

  saasfork_design_system:
    path: ../packages/saasfork_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10

flutter:
  generate: true
  uses-material-design: true
