name: Run Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Setup Melos
        run: |
          dart pub global activate melos
          echo "$(dart pub global bin)" >> $GITHUB_PATH

      - name: Bootstrap Melos
        run: melos bootstrap

      - name: Run Tests
        run: melos run test
