name: Run Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run:  |
          cd packages/saasfork_design_system
          flutter pub get

      - name: Run Tests
        run: |
          cd packages/saasfork_design_system
          flutter test
